### ISSUE TITLE
Trang chủ

### ISSUE THREAD

**Issue by JinJin1503** [JinJin1503/Haiphuthuyvanamchulun#16]
Giao diện Trang chủ cung cấp thông tin tổng quan về trang trại, giới thiệu nhanh các giống cá Koi, các dịch vụ nổi bật và các chương trình khuyến mãi hiện tại.

**Comment by huynhducmanh2005** [comment]
![image](https://github.com/user-attachments/assets/2b5e1bc1-c387-4010-8395-f344cbdc98b0)

**Comment by YenDi05** [comment]
![Image](https://github.com/user-attachments/assets/8b2f6950-4b64-4570-86f2-b8e79ebe1d1d)
