### ISSUE TITLE
Sản phẩm

### ISSUE THREAD

**Issue by JinJin1503** [JinJin1503/Haiphuthuyvanamchulun#18]
Trang này hiển thị thông tin chi tiết về các giống cá Koi mà trang trại cung cấp

**Comment by YenDi05** [comment]
![Image](https://github.com/user-attachments/assets/434fb072-53ae-4771-ac64-967352da05c0)

**Comment by YenDi05** [comment]
![Image](https://github.com/user-attachments/assets/bccd1b8b-973a-4d0c-a22c-4e5bda0af714)
