### ISSUE TITLE
 Liên hệ

### ISSUE THREAD

**Issue by JinJin1503** [JinJin1503/Haiphuthuyvanamchulun#24]
Trang Liên hệ cho phép khách hàng gửi câu hỏi, phản hồi hoặc yêu cầu hỗ trợ từ trang trại

**Comment by Sinnerjudging** [comment]
[Contact.zip](https://github.com/user-attachments/files/17742629/Contact.zip)

**Comment by YenDi05** [comment]
![image](https://github.com/user-attachments/assets/25e2a32e-da80-434d-bf01-3ae6c3c1a318)

**Comment by JinJin1503** [comment]
![image](https://github.com/user-attachments/assets/9fc197ee-f385-4e43-81e8-0cf481478aec)

**Comment by YenDi05** [comment]
![image](https://github.com/user-attachments/assets/6b99b9a1-463f-495a-b8b6-5cd62acdf8bf)
