### ISSUE TITLE
Thiết kế database

### ISSUE THREAD

**Issue by JinJin1503** [JinJin1503/Haiphuthuyvanamchulun#44]
Thiết kế các bảng dữ liệu trong dự án bao gồm: thuộc tính, kiểu dữ liệu và mô tả

**Comment by JinJin1503** [comment]
[Thiết kế Database.docx](https://github.com/user-attachments/files/17605940/Thi.t.k.Database.docx)

**Comment by JinJin1503** [comment]
[Thiết kế Database.docx](https://github.com/user-attachments/files/17606457/Thi.t.k.Database.docx)

**Comment by YenDi05** [comment]
[Thiết kế database.docx](https://github.com/user-attachments/files/17852150/Thi.t.k.database.docx)
