### ISSUE TITLE
Mối quan hệ ràng buộc dữ liệu

### ISSUE THREAD

**Issue by JinJin1503** [JinJin1503/Haiphuthuyvanamchulun#45]
Giải thích chi tiết về thông tin các bảng và liên kết giữa chúng

**Comment by JinJin1503** [comment]
[Mối quan hệ ràng buộc dữ liệu.docx](https://github.com/user-attachments/files/17605954/M.i.quan.h.rang.bu.c.d.li.u.docx)

**Comment by JinJin1503** [comment]
[Mối quan hệ ràng buộc dữ liệu.docx](https://github.com/user-attachments/files/17605963/M.i.quan.h.rang.bu.c.d.li.u.docx)

**Comment by YenDi05** [comment]
[Mối quan hệ ràng buộc dữ liệu.docx](https://github.com/user-attachments/files/17852172/M.i.quan.h.rang.bu.c.d.li.u.docx)
