### ISSUE TITLE
Thanh Menu 

### ISSUE THREAD

**Issue by YenDi05** [JinJin1503/Haiphuthuyvanamchulun#51]

**Comment by JinJin1503** [comment]
![Image](https://github.com/user-attachments/assets/51a13972-0a1d-4131-bf5d-8a8253c26e6a)

**Comment by JinJin1503** [comment]
![Image](https://github.com/user-attachments/assets/79f59c9d-46b4-40fb-aa81-819b5790116d)

**Comment by YenDi05** [comment]
![image](https://github.com/user-attachments/assets/45a550a2-4a50-4352-81b6-7ab8fc6ff3ff)
